sudo: false
language: elixir
elixir:
  - 1.6
otp_release:
  - 20.2
cache:
  directories:
    - _build
    - deps
env:
  global:
    - HEX_USERNAME=bryanjos
before_install:
  - mkdir -p ~/.hex/
  - openssl aes-256-cbc -K $encrypted_36030c2fae51_key -iv $encrypted_36030c2fae51_iv -in hex.config.enc -out ~/.hex/hex.config -d
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
  - mix compile
deploy:
  skip_cleanup: true
  # https://docs.travis-ci.com/user/deployment/script/
  # > `script` must be a scalar pointing to an executable file or command.
  provider: script
  # http://yaml.org/spec/1.2/spec.html#id2779048
  # `>-` indicates the line folding.
  script: >-
    mix deps.get &&
    echo $HEX_PASSPHRASE | mix hex.publish --no-confirm &&
    mix clean &&
    mix deps.clean --all
  on:
    tags: true
